name: VCamdroid
options:
  bundleIdPrefix: com.darusc
  deploymentTarget:
    iOS: "15.0"
settings:
  SWIFT_VERSION: "5.0"
targets:
  VCamdroid:
    type: application
    platform: iOS
    sources:
      - path: VCamdroid
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.darusc.vcamdroid
      INFOPLIST_FILE: VCamdroid/App/Info.plist
      MARKETING_VERSION: "1.0"
      CURRENT_PROJECT_VERSION: "1"
      TARGETED_DEVICE_FAMILY: "1,2"
      IPHONEOS_DEPLOYMENT_TARGET: "15.0"
